# in order to use 'trusty' dist, need this.
# see https://docs.travis-ci.com/user/trusty-ci-environment/
sudo: required

# trust dist provides a modern build chain (as opposed to 'precise' dist)
# which absolves us from having to install compilers and stuff
dist: trusty

language: node_js

matrix:
  include:
    - node_js: '6'
      env: TARGET=test-node
      env: TARGET=test-browser
      env: TARGET=lint
    - node_js: '5'
      env: TARGET=test-node
    - node_js: '4'
      env: TARGET=test-node
    - node_js: 'iojs'
      env: TARGET=test-node
    - node_js: '0.12'
      env: TARGET=test-node
    - node_js: '0.11'
      env: TARGET=test-node
    - node_js: '0.10'
      env: TARGET=test-node
    - node_js: '0.8'
      env: TARGET=test-node

before_install:
  # node 0.8 won't install our dev deps with an out-of-box npm;
  # this upgrades it
  - node ./scripts/upgrade-npm.js

script: travis_retry make $TARGET

addons:
  sauce_connect:
    username: mochajs
    access_key:
      secure: R0HXKtR6F2iDEnItv57BTRyL64XfyIlyyluPLK8G33O/InaQjT3KxGuxevz3nVYIqqnI1MPjYodXcQaqrBOLUVmA2vhBeMHB2OwGc9GAL+HBtB1fh+bQJelkl/XMcTTbC5LIZ6nZjmFnkmjqT3AmUhdDRISgieIFeVY4x48LfiU=

notifications:
  urls:
    # for gitter
    - secure: "EmycFlk48bUvOQ07mxnbcn6T+n3G4wVWuXgrDsUUp6EhJ9866wQK9i+qVhqogWuSEQrGoVaS/vpc/NEYxDP30BD/+nqgvOhVhLVEgtziI85imyV/oUVpArdW3AUmuzCrx7rQCivygjpBmWV9ZcUT5Km4qp1iQhuumy2WbplxrZ4="
  on_success: change
  on_failure: always
